version: '3.7'

services:
  db:
    image: postgres:13-alpine
    container_name: database
    restart: always
    environment:
      POSTGRES_DB: pictapp
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: SBO.4dm1n
    ports:
      - 5434:5432
    volumes:
      - /var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
     PGADMIN_DEFAULT_EMAIL: sergio.barrientos@serbaros.com
     PGADMIN_DEFAULT_PASSWORD: SBO.pg4dm1n
     PGADMIN_LISTEN_PORT: 80
    ports:
      - 8081:80
    volumes:
     - /var/lib/pgadmin
    depends_on:
      - db
      